import Head from "next/head";
import Link from "next/link";
import { Button } from "../components/Button";
import { Inside } from "../components/Inside";
import { Title } from "../components/Title";

export default function Home() {
  return (
    <div className="h-screen w-screen justify-center items-center">
      <Head>
        <title>名言GAFAM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title text="ビッグ・テックを愛する人に捧ぐ名言"/>

      <Inside />

      <Link href="/selection">
        <Button text="始める"/>
      </Link>
    </div>
  );
}
