import Head from "next/head";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-white text-7xl">ビッグ・テックを愛する人へ捧ぐ</h1>

        <div>
          <p>
            興奮する名言を心に刻む。
            <br />
            そして、 自分を奮い立たせよ。
            <br />
            何か行動したい時、
            <br />
            出来ない時、困った時、
            <br />
            貴方の気持ちが前向きになりますように。
          </p>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
